### ISSUE TITLE
Missing dependency when trying to compile the KRS acceleration examples

### ISSUE THREAD

**Issue by kimonk** [Xilinx/KRS#10]
After installing KRS and following the steps described here: 

https://xilinx.github.io/KRS/sphinx/build/html/docs/examples/0_ros2_publisher.html

I get an error when running _colcon build --merge-install_  
The error message is:

"Starting >>> accelerated_doublevadd_publisher
--- stderr: accelerated_doublevadd_publisher                          
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findvitis_common.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "vitis_common", but CMake did not find one.

  Could not find a package configuration file provided by "vitis_common" with
  any of the following names:

    vitis_commonConfig.cmake
    vitis_common-config.cmake

  Add the installation prefix of "vitis_common" to CMAKE_PREFIX_PATH or set
  "vitis_common_DIR" to a directory containing one of the above files.  If
  "vitis_common" provides a separate development package or SDK, be sure it
  has been installed.

---
Failed   <<< accelerated_doublevadd_publisher [0.82s, exited with code 1]"

Apparently some dependency is missing from the repository.

**Comment by GZanni-mkl** [comment]
+1 - It happened the same to me

**Comment by vmayoral** [comment]
Thanks to both for reporting. It took a while for Xilinx to react and accept pending PRs. https://github.com/Xilinx/KRS/blob/main/krs.repos is now updated.

Re-try with it please.

**Comment by vmayoral** [comment]
@kimonk, can you give it a try and report if you still encounter issues?

**Comment by vmayoral** [comment]
ping @jasvinderkhurana, please confirm and/or resolve as appropriate.

**Comment by kimonk** [comment]
It worked for me. Now I can build the example as described in the guide. I'm closing this issue.

**Comment by vmayoral** [comment]
Thanks @kimonk!
