### ISSUE TITLE
Add capability section to KRS landing page

### ISSUE THREAD

**Issue by jasvinderkhurana** [Xilinx/KRS#21]
New capabilities (hypervisor, platform, emulation, mount/unmount) are missing in the KRS landing [page](https://github.com/Xilinx/KRS/blob/main/README.md). Refer [this](https://github.com/Xilinx/KRS/commit/c25d13b6d84988bb77c3826ba34aa9bb8b496c0b) commit.

**Comment by vmayoral** [comment]
Good catch @jasvinderkhurana. See https://github.com/Xilinx/KRS/pull/22.

#22 closes #21.
