### ISSUE TITLE
Add tags to this repository

### ISSUE THREAD

**Issue by vmayoral** [Xilinx/KRS#25]
@jasvinderkhurana can you please add appropriate tags to this repo so that it becomes easier to find it and index it (search engines, etc).

Please use the following ones **at least** (or similar, you may need to reword things a bit):
- `kria`
- `hardware`
- `fpga`
- `robotics`
- `ros`
- `ros2`
- `robot-operating-system`
- `hardware-acceleration`
- `acceleration`
- `kernels`
- `gpu`

**Comment by jasvinderkhurana** [comment]
@vmayoral Thanks for your suggestion. I have incorporated the required tags (topics). will keep it updated as and when new functionality is integrated.
