### ISSUE TITLE
Improve repo's description

### ISSUE THREAD

**Issue by vmayoral** [Xilinx/KRS#26]
@jasvinderkhurana can we please improve the repo's description? I'd suggest to shortly define what KRS is.

**Comment by jasvinderkhurana** [comment]
Thanks @vmayoral ! I have updated the description

**Comment by vmayoral** [comment]
@jasvinderkhurana can we please cut the description a bit shorter? Only to:

*The Kria Robotics Stack (KRS) is a ROS 2 superset for industry, an integrated set of robot libraries and utilities to accelerate the development, maintenance and commercialization of industrial-grade robotic solutions while using adaptive computing*.

**Comment by vmayoral** [comment]
Also, I can't re-open tickets. Can you enable me to do so with permissions?
