### ISSUE TITLE
Broken link to examples

### ISSUE THREAD

**Issue by tomasthoresen** [Xilinx/KRS#27]
The last line on this page includes a link that is broken. Please fix this link.

It's from this page "https://github.com/Xilinx/KRS/blob/main/sphinx/source/docs/install.md" and the line is:
"Now's time to build and run some **examples**."

The link "examples" points to this: "https://github.com/Xilinx/KRS/blob/main/sphinx/source/docs/features/ros2centric"

thx!

**Comment by jasvinderkhurana** [comment]
@tomasthoresen, Thanks a lot for pointing the issue. The link is fixed now.
