### ISSUE TITLE
link Vitis 2020.2.2 outdated

### ISSUE THREAD

**Issue by femust** [Xilinx/KRS#34]
Hey,

there is a minor issue in the instructions
```
- the Vitis `2020.2.2` suite (Vitis, Vivado, Vitis HLS) (`install instructions <https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis/2020-2.html>`_)
```

a link points to the "blank website"

![image](https://user-images.githubusercontent.com/26916586/151656769-3999189e-6e7c-49ee-a9e5-acf4561ba743.png)

**Comment by vmayoral** [comment]
This sounds about right, https://www.xilinx.com/support/download.html doesn't show Vitis 2020.2.2 anymore. Only Vitis 2020.3 seems available but there's no KRS tested release for this.

@jasvinderkhurana and @giuliocorradi deferring to you on this.

**Comment by giuliocorradi** [comment]
Vitis as many other Xilinx tools follow a rolling update - you can find 2020.2 here https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis/archive-vitis.html

**Comment by femust** [comment]
Yeap, I figured this out :) 

I guess for future newcomers it would be nice to have this info since at the beginning it may be confusing and may encourage people to install the newest software and as far as I understood the Vitis 2021.x.x has not been integrated yet with  KRS.

**Comment by giuliocorradi** [comment]
good suggestion to include in the KRS install instructions..**.if you do not  find the version 20xx.x.x,  look in the archive**

**Comment by jasvinderkhurana** [comment]
tools are now updated, will add proper instructions to install.
