### ISSUE TITLE
# KRS Beta build error

### ISSUE THREAD

**Issue by surender009** [Xilinx/KRS#42]
### steps followed from [KRS](https://xilinx.github.io/KRS/sphinx/build/html/docs/install.html)

In file included from /scratch/krs_beta/src/perception/image_pipeline/image_proc/src/rectify_resize_fpga_integrated_xrt.cpp:35:
/scratch/krs_beta/src/perception/image_pipeline/image_proc/include/image_proc/rectify_resize_fpga_integrated_xrt.hpp:37:10: fatal error: experimental/xrt_bo.h: No such file or directory
   37 | #include "experimental/xrt_bo.h"

**Comment by vmayoral** [comment]
@surender009, merging this into https://github.com/Xilinx/KRS/issues/41 since the issue apparently the same.
