### ISSUE TITLE
CMake Error when building image_publisher

### ISSUE THREAD

**Issue by kevinkeryk** [Xilinx/KRS#44]
Installed ROS 2 packages under Ubuntu 20.04 along with Vitis 2021.2 tools installed following these instructions:
http://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html

Talker and listener examples are working but now when I follow the beta install directions for KRS:
https://github.com/vmayoral/KRS/blob/beta/sphinx/source/docs/install.md

I am running into the following fatal error during the `colcon build --merge-install` step:

```
Starting >>> image_publisher
Finished <<< launch_pytest [2.60s]                                                                                                                                                                
Starting >>> opencv_tests
Finished <<< tracetools_test [2.81s]                                                                                                                                                           
Starting >>> test_tracetools
Finished <<< simple_adder [4.52s]                                                                                                                                                                  
Starting >>> vision_opencv
Finished <<< streaming_k2k_mm_xrt [4.21s]                                                                                                                            
--- stderr: image_publisher                                                                                                                                          
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findament_cuda.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cuda", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cuda" with
  any of the following names:

    ament_cudaConfig.cmake
    ament_cuda-config.cmake

  Add the installation prefix of "ament_cuda" to CMAKE_PREFIX_PATH or set
  "ament_cuda_DIR" to a directory containing one of the above files.  If
  "ament_cuda" provides a separate development package or SDK, be sure it has
  been installed.


---
Failed   <<< image_publisher [2.51s, exited with code 1]
```

I tried the solution mentioned in https://github.com/Xilinx/KRS/issues/35 since they look very similar, but still seeing the issue.

This causes other package builds to abort as well. Has anyone else run into this issue?

**Comment by vmayoral** [comment]
@kevinkeryk I think you have a mix in your workspace from previous iterations. The package that's complaining is within https://github.com/Xilinx/KRS/blob/main/krs_rolling.repos#L19-L22, note it's using the `beta` branch. Are you by chance using the `ros2` branch? 
- `ros2`: uses `ament_cuda` https://github.com/ros-acceleration/image_pipeline/blob/ros2/image_publisher/CMakeLists.txt#L13 (that's what I'm working on right now, cutting edge, you should not be using this)
- `beta`: no `ament_cuda` https://github.com/ros-acceleration/image_pipeline/blob/beta/image_publisher/CMakeLists.txt

Clean the whole workspace up and re-start (remove everything).

**Comment by kevinkeryk** [comment]
Okay, I cleaned up my workspace and started following this instead to move past this issue:

https://github.com/Xilinx/KRS/blob/main/sphinx/source/docs/install.md
