### ISSUE TITLE
Cross compile and generate CPU binaries and accelerators

### ISSUE THREAD

**Issue by lharwood0** [Xilinx/KRS#89]
I found that when I run the command:
$ colcon build --build-base=build-kr260-ubuntu --install-base=install-kr260-ubuntu --merge-install --mixin kr260
that it does not compile all the way.  However when I run
$ colcon build --executor sequential --build-base=build-kr260-ubuntu --install-base+install-kr260-ubuntu --merge-install --mixin kr260 --cmake-args -DNOKERNELS=false

this seems to work.  Without the "--executor sequential" portion, I find that my terminal crashes mid compiling with no error.  This seems to have solved the issue

**Comment by jasvinderkhurana** [comment]
@lharwood0 , Thanks for reporting, I have updated the documentation
